# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

---
- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:
  - name: Run the OE setup script
    script: ../oe-env-prepare.ps1

  - import_role:
      name: windows/openenclave
      tasks_from: validation.yml

  - import_role:
      name: windows/az-dcap-client
      tasks_from: validation.yml
